runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.php
  
- url: /stylesheets
  static_dir: stylesheets
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

# [START env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/carbide-oarlock-196011:europe-west3:test-database;dbname=input
  MYSQL_USER: test_user
  MYSQL_PASSWORD: password
# [END env]
