runtime: php55
api_version: 1
  
handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: index.php

#[START env]
env_variables:
  #MYSQL_DSN: mysql:unix_socket=/cloudsql/test-database;dbname=DATABASE
  MYSQL_DSN: mysql:unix_socket=/test-database;dbname=DATABASE
  MYSQL_USER: admin
  MYSQL_PASSWORD: 9e4Uf3QM
#[END env]